import http from 'node:http';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import pg from 'pg';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const PORT=Number(process.env.PORT||3000);
const SOURCE='https://app-p7vcr6.v2.appdeploy.ai';
const API_SOURCE='https://api-v2.appdeploy.ai/app/app-p7vcr6';
const DATABASE_URL=process.env.DATABASE_URL||'';
const pool=DATABASE_URL?new pg.Pool({connectionString:DATABASE_URL,ssl:{rejectUnauthorized:false}}):null;
let mem={};

const json=(res,status,obj)=>{res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(obj));};
const readBody=async req=>{let s='';for await(const c of req)s+=c;try{return JSON.parse(s||'{}')}catch{return{}}};
const uid=()=>globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`;
async function init(){if(pool)await pool.query('create table if not exists qa_state(key text primary key,value jsonb not null)');}
async function get(key,def=null){if(!pool)return key in mem?mem[key]:def;const r=await pool.query('select value from qa_state where key=$1',[key]);return r.rows[0]?.value??def;}
async function set(key,value){if(!pool){mem[key]=value;return;}await pool.query('insert into qa_state(key,value) values($1,$2::jsonb) on conflict(key) do update set value=excluded.value',[key,JSON.stringify(value)]);}
const yearOf=u=>Number(u.searchParams.get('year'))||2026;
const rowsKey=(name,y)=>`${name}:${y}`;
async function fetchSourceJson(p){const r=await fetch(API_SOURCE+p,{headers:{accept:'application/json'}});if(!r.ok)throw new Error(`source ${r.status} ${p}`);return r.json();}
async function migrateYear(y){const out={year:y};const specs=[['returns',`/api/data?year=${y}`],['processing',`/api/processing?year=${y}`],['audits',`/api/audits?year=${y}`],['quality',`/api/quality?year=${y}`],['focus',`/api/monthly-focus?year=${y}`],['experiments',`/api/experiments?year=${y}`],['foreign',`/api/foreign?year=${y}`],['kpi',`/api/kpi?year=${y}`]];for(const [name,p] of specs){try{const d=await fetchSourceJson(p);if(name==='returns')await set(rowsKey('returns',y),d.rows||[]);if(name==='processing')await set(rowsKey('processing',y),d.monthly||Array(12).fill(0));if(name==='audits'){await set(rowsKey('audits',y),d.rows||[]);await set(rowsKey('auditNcr',y),d.nonconformMonthly||Array(12).fill(0));}if(name==='quality')await set(rowsKey('quality',y),d.rows||[]);if(name==='focus')await set(rowsKey('focus',y),d.rows||[]);if(name==='experiments')await set(rowsKey('experiments',y),d.rows||[]);if(name==='foreign'){await set(rowsKey('foreign',y),d.rows||[]);await set(rowsKey('foreignActual',y),d.actual??0);await set(rowsKey('foreignTarget',y),d.target??5);}if(name==='kpi')await set(rowsKey('kpi',y),d);out[name]=d.rows?.length??d.monthly?.length??'ok';}catch(e){out[name]=`error:${e.message}`;}}const prod=[];for(let m=1;m<=12;m++){try{const d=await fetchSourceJson(`/api/production?year=${y}&month=${m}`);prod.push({month:m,rows:d.rows||[]});}catch{prod.push({month:m,rows:[]});}}await set(rowsKey('production',y),prod);out.production=prod.reduce((s,x)=>s+x.rows.length,0);return out;}
async function migrateAll(){let years=[2026];try{const d=await fetchSourceJson('/api/years');if(Array.isArray(d.years)&&d.years.length)years=d.years.map(Number).filter(Boolean);}catch{}const summary=[];for(const y of years)summary.push(await migrateYear(y));await set('years',years);await set('migratedAt',new Date().toISOString());await set('migrationSummary',summary);return summary;}
await init();if(!(await get('migratedAt')))try{console.log('migration',JSON.stringify(await migrateAll()));}catch(e){console.error('migration failed',e);}

async function sendLocalBanner(res){try{const b64=await fs.readFile(path.join(__dirname,'public','resources','qa-team-top-banner.b64'),'utf8');const b=Buffer.from(b64.trim(),'base64');res.writeHead(200,{'content-type':'image/jpeg','cache-control':'no-store'});res.end(b);}catch{return json(res,404,{error:'banner not found'});}}

const bannerPatch=`<style id="railway-banner-fix">img[data-railway-banner]{width:100%!important;height:auto!important;display:block!important;object-fit:cover!important}</style><script>(function(){const NEW='/resources/qa-team-top-banner.jpg?v=20260914-1715';function fix(){try{const imgs=[...document.querySelectorAll('img')];let c=imgs.filter(i=>{const r=i.getBoundingClientRect();return r.top<750&&(r.width>700||i.naturalWidth>1200)});c.sort((a,b)=>(b.getBoundingClientRect().width*b.getBoundingClientRect().height)-(a.getBoundingClientRect().width*a.getBoundingClientRect().height));if(c[0]&&!c[0].src.includes('qa-team-top-banner.jpg')){c[0].setAttribute('data-railway-banner','1');c[0].src=NEW;c[0].srcset='';}for(const el of document.querySelectorAll('*')){const r=el.getBoundingClientRect();if(r.top>750||r.width<700)continue;const bg=getComputedStyle(el).backgroundImage;if(bg&&bg!=='none'&&(bg.includes('banner')||bg.includes('qa-team')||bg.includes('appdeploy'))){el.style.backgroundImage='url('+NEW+')';el.style.backgroundSize='cover';el.style.backgroundPosition='center';}}}catch(e){}}new MutationObserver(fix).observe(document.documentElement,{subtree:true,childList:true,attributes:true,attributeFilter:['src','srcset','style','class']});window.addEventListener('DOMContentLoaded',fix);window.addEventListener('load',fix);setTimeout(fix,100);setTimeout(fix,500);setTimeout(fix,1500);})();</script>`;

async function proxyStatic(req,res){const u=new URL(req.url,'http://local');if(u.pathname==='/resources/qa-team-top-banner.jpg'||u.pathname==='/resources/qa-team-top-banner.png'||u.pathname==='/qa-team-top-banner.png')return sendLocalBanner(res);const target=SOURCE+(u.pathname==='/'?'/':u.pathname)+u.search;const r=await fetch(target,{redirect:'follow'});if(!r.ok)return json(res,r.status,{error:'not found'});const type=r.headers.get('content-type')||'application/octet-stream';const isText=type.includes('text/')||type.includes('javascript')||type.includes('json');if(!isText){const b=Buffer.from(await r.arrayBuffer());res.writeHead(200,{'content-type':type,'cache-control':'no-cache'});return res.end(b);}let text=await r.text();if(type.includes('text/html')){const host=req.headers.host||'dodram-gimje-qa-production.up.railway.app';const origin=`https://${host}`;text=text.replaceAll(encodeURIComponent(API_SOURCE),encodeURIComponent(origin)).replaceAll(API_SOURCE,origin).replace(/<script async src="https:\/\/v2\.appdeploy\.ai\/shared\/js\/overlay\.js"[^>]*><\/script>/g,'');text=text.replace(/(?:https:\/\/app-p7vcr6\.v2\.appdeploy\.ai\/)?resources\/qa-team-top-banner\.(?:png|jpg|jpeg|webp)(?:\?[^"']*)?/gi,'/resources/qa-team-top-banner.jpg?v=20260914-1715');if(text.includes('</body>'))text=text.replace('</body>',bannerPatch+'</body>');else text+=bannerPatch;}res.writeHead(200,{'content-type':type,'cache-control':'no-store'});res.end(text);}

async function handleApi(req,res,u){const p=u.pathname,y=yearOf(u),method=req.method||'GET';if(p==='/health')return json(res,200,{ok:true,db:!!pool,migratedAt:await get('migratedAt'),migrationSummary:await get('migrationSummary',[])});if(p==='/api/migrate'&&method==='POST')return json(res,200,{ok:true,summary:await migrateAll()});if(p==='/api/admin/login'&&method==='POST')return json(res,200,{ok:true});if(p==='/api/years'&&method==='GET')return json(res,200,{years:await get('years',[2026])});if(p==='/api/data'&&method==='GET')return json(res,200,{rows:await get(rowsKey('returns',y),[])});if(p==='/api/processing'&&method==='GET')return json(res,200,{year:y,monthly:await get(rowsKey('processing',y),Array(12).fill(0))});if(p==='/api/processing/save'&&method==='POST'){const b=await readBody(req),yy=Number(b.year)||y,monthly=Array.isArray(b.monthly)?b.monthly.map(Number):[];await set(rowsKey('processing',yy),monthly);return json(res,200,{ok:true});}if(p==='/api/production'&&method==='GET'){const m=Number(u.searchParams.get('month')),a=await get(rowsKey('production',y),[]);return json(res,200,{year:y,month:m,rows:a.find(x=>Number(x.month)===m)?.rows||[]});}if(p==='/api/quality'&&method==='GET')return json(res,200,{year:y,rows:await get(rowsKey('quality',y),[])});if(p==='/api/quality/save'&&method==='POST'){const b=await readBody(req),yy=Number(b.year)||y,a=await get(rowsKey('quality',yy),[]),id=String(b.id||''),row={id:id||uid(),no:Number(b.no)||1,date:String(b.date||''),completedDate:String(b.completedDate||''),location:String(b.location||''),status:String(b.status||'미정'),request:String(b.request||''),note:String(b.note||''),before:String(b.before||''),after:String(b.after||'')};const i=a.findIndex(x=>String(x.id)===id);if(i>=0)a[i]=row;else a.push(row);await set(rowsKey('quality',yy),a);return json(res,200,{ok:true,row});}if(p==='/api/quality/delete'&&method==='POST'){const b=await readBody(req),yy=Number(b.year)||y,a=await get(rowsKey('quality',yy),[]);await set(rowsKey('quality',yy),a.filter(x=>String(x.id)!==String(b.id)));return json(res,200,{ok:true});}if(p==='/api/monthly-focus'&&method==='GET')return json(res,200,{year:y,rows:await get(rowsKey('focus',y),[])});if(p==='/api/experiments'&&method==='GET')return json(res,200,{year:y,rows:await get(rowsKey('experiments',y),[])});if(p==='/api/audits'&&method==='GET')return json(res,200,{year:y,rows:await get(rowsKey('audits',y),[]),nonconformMonthly:await get(rowsKey('auditNcr',y),Array(12).fill(0))});if((p==='/api/foreign'||p==='/api/foreign/list')&&(method==='GET'||method==='POST')){let yy=y;if(method==='POST')yy=Number((await readBody(req)).year)||y;return json(res,200,{rows:await get(rowsKey('foreign',yy),[]),actual:await get(rowsKey('foreignActual',yy),0),target:await get(rowsKey('foreignTarget',yy),5)});}if(p==='/api/kpi'&&method==='GET')return json(res,200,await get(rowsKey('kpi',y),{year:y}));return json(res,404,{error:'API not found'});}

http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://x');if(u.pathname==='/health'||u.pathname.startsWith('/api/'))return handleApi(req,res,u);return proxyStatic(req,res);}catch(e){console.error(e);json(res,500,{error:e.message});}}).listen(PORT,'0.0.0.0',()=>console.log('QA dashboard',PORT));
